seattle:
  zone: 10
  lonMin1: -125
  lonMax1: -123.5
  latMin1: 48
  latMax1: 48.7
  lonMin2: -122.8
  lonMax2: -122
  latMin2: 47.
  latMax2: 48.2
  minPoints: 20
  region: P
  tss: '148'
  srid: >
          INSERT into spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext)
          values (
              932610,
              'epsg',
              32610,
              '+proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs ',
              'PROJCS[
                  "WGS 84 / UTM zone 10N",
                  GEOGCS[
                      "WGS 84",
                      DATUM[
                          "WGS_1984",
                          SPHEROID[
                              "WGS 84",
                              6378137,
                              298.257223563,
                              AUTHORITY["EPSG","7030"]
                          ],
                          AUTHORITY["EPSG","6326"]
                      ],
                      PRIMEM[
                          "Greenwich",
                          0,
                          AUTHORITY["EPSG","8901"]
                      ],
                      UNIT[
                          "degree",
                          0.01745329251994328,
                          AUTHORITY["EPSG","9122"]
                      ],
                      AUTHORITY["EPSG","4326"]
                  ],
                  UNIT[
                      "metre",
                      1,
                      AUTHORITY["EPSG","9001"]
                  ],
                  PROJECTION["Transverse_Mercator"],
                  PARAMETER["latitude_of_origin",0],
                  PARAMETER["central_meridian",-123],
                  PARAMETER["scale_factor",0.9996],
                  PARAMETER["false_easting",500000],
                  PARAMETER["false_northing",0],
                  AUTHORITY["EPSG","32610"],
                  AXIS["Easting",EAST],
                  AXIS["Northing",NORTH]
              ]'
          )
          ON CONFLICT (srid) DO NOTHING
  epsg: 32610

houston:
  zone: 15
  lonMin: -96.
  lonMax: -91.
  latMin: 28.
  latMax: 30.
  stepSize: 0.1
  region: G
